--// Libary

local cloneref = cloneref or function (obj)
    return obj
end

local Players = cloneref(game:GetService("Players"))
local Workspace = cloneref(game:GetService("Workspace"))
local ReplicatedStorage = cloneref(game:GetService("ReplicatedStorage"))
local Lighting = cloneref(game:GetService("Lighting"))
local StarterGui = cloneref(game:GetService("StarterGui"))
local StarterPack = cloneref(game:GetService("StarterPack"))
local StarterPlayer = cloneref(game:GetService("StarterPlayer"))
local Teams = cloneref(game:GetService("Teams"))
local SoundService = cloneref(game:GetService("SoundService"))
local Chat = cloneref(game:GetService("Chat"))
local TweenService = cloneref(game:GetService("TweenService"))
local RunService = cloneref(game:GetService("RunService"))
local HttpService = cloneref(game:GetService("HttpService"))
local TextService = cloneref(game:GetService("TextService"))
local LocalizationService = cloneref(game:GetService("LocalizationService"))
local ContextActionService = cloneref(game:GetService("ContextActionService"))
local CollectionService = cloneref(game:GetService("CollectionService"))
local UserInputService = cloneref(game:GetService("UserInputService"))
local GuiService = cloneref(game:GetService("GuiService"))
local ContentProvider = cloneref(game:GetService("ContentProvider"))
local MarketplaceService = cloneref(game:GetService("MarketplaceService"))
local PathfindingService = cloneref(game:GetService("PathfindingService"))
local PolicyService = cloneref(game:GetService("PolicyService"))
local ProximityPromptService = cloneref(game:GetService("ProximityPromptService"))
local Stats = cloneref(game:GetService("Stats"))
local VRService = cloneref(game:GetService("VRService"))
local VoiceChatService = cloneref(game:GetService("VoiceChatService"))
local SocialService = cloneref(game:GetService("SocialService"))
